baseURL = "https://kutty.netlify.app"
title = "Kutty"

disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Praveen Juge"
  sitename = "Kutty"
  ogimage = "/images/og.png"
  description = "Kutty is a set of accessible and reusable components for building web applications."

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false